// <auto-generated />
namespace OpenInvoicePeru.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CorreoEmpresa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CorreoEmpresa));
        
        string IMigrationMetadata.Id
        {
            get { return "201706230346178_Correo-Empresa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
